name: Build and Release

on:
  push:
    # trigger on branches like release-v0.1.0 or release-v0.1.0-Alpha
    branches:
      - 'release-v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      # Strip off the `release-v` prefix, keep the full version including suffix.
      FULL_VERSION: ${{ replace(github.ref_name, 'release-v', '') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build fat JAR
        run: ./gradlew generateGrammarSource shadowJar

      - name: Prepare release package
        run: |
          mkdir release
          # Copy the built JAR (whatever Gradle named it) and rename it to include the full version
          cp build/libs/minjc-*.jar release/minjc-${FULL_VERSION}.jar
          cp -r examples        release/
          cp README.md          release/
          cd release
          zip -r minjc-${FULL_VERSION}.zip .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          # Tag it `v0.1.0-Alpha` (or whatever your branch’s suffix is)
          tag_name: v${{ env.FULL_VERSION }}
          release_name: Release v${{ env.FULL_VERSION }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/minjc-${{ env.FULL_VERSION }}.zip
          asset_name: minjc-${{ env.FULL_VERSION }}.zip
          asset_content_type: application/zip
